### ISSUE TITLE
Crash to Desktop

### ISSUE THREAD

**Issue by ESPhacker** [krzysk1/long_ez#2]
Many thanks Krzysztof for all the updates you made since 10 Aug 2020. All work fine, also with the latest Alpha 2.05.01.01.
Exept the long_ez. It crashes AFS2 to the desktop. Please find the log attached.
Best regards, Tom.
[Crashlog.txt](https://github.com/krzysk1/long_ez/files/5112142/Crashlog.txt)

**Comment by krzysk1** [comment]
thx for notification. I'l check it soon

**Comment by krzysk1** [comment]
seems that  files from different versions have been mixed. Please remove all files and upload newest package
